# To run only the application external services:
# docker-compose up
#
# To build the osTicket image and run it alongside services:
# docker-compose --profile app up --build
version: '3.9'

services:
  osticket:
    build: .
    profiles:
      - app
    image: osticket
    restart: unless-stopped
    depends_on: 
      - db
    ports:
      - 8080:80
    networks:
      - osticket
    environment:
      - ADMIN_EMAIL=admin@example.com
      - DBTYPE=mysql
      - DBHOST=db
      - DBNAME=osticket
      - DBUSER=osticket
      - DBPASS=Test1234
      - SALT=f75354578b0541bca0acda932ca9774d
  db:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=Root1234
      - MARIADB_DATABASE=osticket
      - MARIADB_USER=osticket
      - MARIADB_PASSWORD=Test1234
    volumes: 
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - osticket
  adminer:
    image: adminer
    depends_on: 
      - db
    ports:
      - 8081:8080
    networks:
      - osticket
volumes:
  mariadb_data:
networks:
  osticket:
    attachable: true
    name: osticket
