# docker-compose --env-file unitely.env up -d
# docker-compose down

version: '3.9'

services:

##################################################
#####                Mariadb                 #####
##################################################
  db:
    image: mariadb
    hostname: db
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_DATABASE
    volumes: 
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - osticket

##################################################
#####                Adminer                 #####
##################################################
  adminer:
    image: adminer
    hostname: adminer
    restart: unless-stopped
    depends_on: 
      - db
    ports:
      - 8080:8080
    networks:
      - osticket

##################################################
#####               osTicket                 #####
##################################################
  osticket:
    image: ghcr.io/centeva/osticket:1.16.0-Unitely.2
    hostname: osticket
    restart: unless-stopped
    depends_on: 
      - db
    ports:
      - 80:80
    environment:
      - ADMIN_EMAIL
      - DBHOST
      - DBNAME
      - DBPASS
      - DBTYPE
      - DBUSER
      - SALT
    networks:
      - osticket

##################################################
#####               NETWORKS                 #####
##################################################

networks:
  osticket:
    attachable: true
    name: osticket

volumes:
  mariadb_data:
